import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import { anton } from "@/utils/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-[100vh]  tracking-wide`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}

